#### Import Turicreate

In [1]:
import turicreate
from math import log

#### Import King County House Price Dataset

In [2]:
sales = turicreate.SFrame('home_data.sframe/')

#### Additional features which are functions of the original variables added to the dataset

In [12]:
sales['bedrooms_squared'] = sales['bedrooms'].apply(lambda x:x**2)
sales['bed_bath_rooms'] = sales['bathrooms']*sales['bedrooms']
sales['log_sqft_living'] = sales['sqft_living'].apply(lambda x:log(x))
sales['lat_plus_long'] = sales['lat'] + sales['long']

#### A snapshot of the final dataset we would be working with in building the models

In [13]:
sales

Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	float
	floors	float
	waterfront	int
	view	int
	condition	int
	grade	float
	sqft_above	float
	sqft_basement	float
	yr_built	float
	yr_renovated	float
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float
	bedrooms_squared	float
	bed_bath_rooms	float
	log_sqft_living	float
	lat_plus_long	float

Rows: 21613

Data:
+------------+---------------------------+-----------+----------+-----------+
|     id     |            date           |   price   | bedrooms | bathrooms |
+------------+---------------------------+-----------+----------+-----------+
| 7129300520 | 2014-10-13 00:00:00+00:00 |  221900.0 |   3.0    |    1.0    |
| 6414100192 | 2014-12-09 00:00:00+00:00 |  538000.0 |   3.0    |    2.25   |
| 5631500400 | 2015-02-25 00:00:00+00:00 |  180000.0 |   2.0    |    1.0    |
| 2487200875 | 2014-12-09 00:00:00+00:00 |  604000.0 |   4.0    |    3.0    |
| 1954400510 | 2015-02-18 00:00:00+00:00 |  510000.0 |   3.0    |    2.0    |
| 7237550310 | 2014-05-12 00:00:00+00:00 | 1225000.0 |   4.0    |    4.5    |
| 1321400060 | 2014-06-27 00:00:00+00:00 |  257500.0 |   3.0    |    2.25   |
| 2008000270 | 2015-01-15 00:00:00+00:00 |  291850.0 |   3.0    |    1.5    |
| 2414600126 | 2015-04-15 00:00:00+00:00 |  229500.0 |   3.0    |    1.0    |
| 3793500160 | 2015-03-12 00:00:00+00:00 |  323000.0 |   3.0    |    2.5    |
+------------+---------------------------+-----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade |
+-------------+----------+--------+------------+------+-----------+-------+
|    1180.0   |  5650.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    2570.0   |  7242.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    770.0    | 10000.0  |  1.0   |     0      |  0   |     3     |  6.0  |
|    1960.0   |  5000.0  |  1.0   |     0      |  0   |     5     |  7.0  |
|    1680.0   |  8080.0  |  1.0   |     0      |  0   |     3     |  8.0  |
|    5420.0   | 101930.0 |  1.0   |     0      |  0   |     3     |  11.0 |
|    1715.0   |  6819.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    1060.0   |  9711.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1780.0   |  7470.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1890.0   |  6560.0  |  2.0   |     0      |  0   |     3     |  7.0  |
+-------------+----------+--------+------------+------+-----------+-------+
+------------+---------------+----------+--------------+---------+-------------+
| sqft_above | sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+------------+---------------+----------+--------------+---------+-------------+
|   1180.0   |      0.0      |  1955.0  |     0.0      |  98178  | 47.51123398 |
|   2170.0   |     400.0     |  1951.0  |    1991.0    |  98125  | 47.72102274 |
|   770.0    |      0.0      |  1933.0  |     0.0      |  98028  | 47.73792661 |
|   1050.0   |     910.0     |  1965.0  |     0.0      |  98136  |   47.52082  |
|   1680.0   |      0.0      |  1987.0  |     0.0      |  98074  | 47.61681228 |
|   3890.0   |     1530.0    |  2001.0  |     0.0      |  98053  | 47.65611835 |
|   1715.0   |      0.0      |  1995.0  |     0.0      |  98003  | 47.30972002 |
|   1060.0   |      0.0      |  1963.0  |     0.0      |  98198  | 47.40949984 |
|   1050.0   |     730.0     |  1960.0  |     0.0      |  98146  | 47.51229381 |
|   1890.0   |      0.0      |  2003.0  |     0.0      |  98038  | 47.36840673 |
+------------+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -122.25677536 |     1340.0    | ... |
|  -122.3188624 |     1690.0    | ... |
| -122.23319601 |     2720.0    | ... |
| -122.39318505 |     1360.0    | ... |
| -122.04490059 |     1800.0    | ... |
| -122.00528655 |     4760.0    | ... |
| -122.32704857 |     2238.0    | ... |
| -122.31457273 |     1650.0    | ... |
| -122.33659507 |     1780.0    | ... |
|  -122.0308176 |     2390.0    | ... |
+---------------+---------------+-----+
[21613 rows x 25 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

#### splitting the dataset into train & test datasets

In [14]:
train_data,test_data = sales.random_split(.8,seed=0)

#### Getting the means of the newly added datasets

In [16]:
print (test_data['bedrooms_squared'].mean())
print (test_data['bed_bath_rooms'].mean())
print (test_data['log_sqft_living'].mean())
print (test_data['lat_plus_long'].mean())

12.4466777015843
7.503901631591394
7.550274679645938
-74.65333497217308

#### Multiple regression models

In [18]:
model1 = turicreate.linear_regression.create(train_data, target = 'price', features = ['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long'], validation_set = None, verbose = False)
model2 = turicreate.linear_regression.create(train_data, target = 'price', features = ['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'bed_bath_rooms'], validation_set = None, verbose = False)
model3 = turicreate.linear_regression.create(train_data, target = 'price', features = ['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'bed_bath_rooms', 'bedrooms_squared','log_sqft_living','lat_plus_long'], validation_set = None, verbose = False)

#### Coefficients of the 3 models

In [20]:
model1.coefficients

Columns:
	name	str
	index	str
	value	float
	stderr	float

Rows: 6

Data:
+-------------+-------+---------------------+--------------------+
|     name    | index |        value        |       stderr       |
+-------------+-------+---------------------+--------------------+
| (intercept) |  None |  -56140675.74114427 | 1649985.420135553  |
| sqft_living |  None |  310.26332577692136 | 3.1888296040737765 |
|   bedrooms  |  None |  -59577.11606759667 | 2487.2797732245012 |
|  bathrooms  |  None |  13811.840541653264 | 3593.5421329670735 |
|     lat     |  None |  629865.7894714845  | 13120.710032363884 |
|     long    |  None | -214790.28516471002 | 13284.285159576597 |
+-------------+-------+---------------------+--------------------+
[6 rows x 4 columns]

In [21]:
model2.coefficients

Columns:
	name	str
	index	str
	value	float
	stderr	float

Rows: 7

Data:
+----------------+-------+---------------------+--------------------+
|      name      | index |        value        |       stderr       |
+----------------+-------+---------------------+--------------------+
|  (intercept)   |  None |  -54410676.1071702  | 1650405.1652726454 |
|  sqft_living   |  None |  304.44929805407946 |  3.20217535637094  |
|    bedrooms    |  None | -116366.04322451768 | 4805.5496654858225 |
|   bathrooms    |  None |  -77972.33050970349 | 7565.059910947983  |
|      lat       |  None |  625433.8349445503  | 13058.353097300462 |
|      long      |  None | -203958.60289731968 | 13268.128370009661 |
| bed_bath_rooms |  None |  26961.624907583264 | 1956.3656155588428 |
+----------------+-------+---------------------+--------------------+
[7 rows x 4 columns]

In [22]:
model3.coefficients

Columns:
	name	str
	index	str
	value	float
	stderr	float

Rows: 10

Data:
+------------------+-------+---------------------+--------------------+
|       name       | index |        value        |       stderr       |
+------------------+-------+---------------------+--------------------+
|   (intercept)    |  None |  -52974974.06892153 | 1615194.942821453  |
|   sqft_living    |  None |  529.1964205687523  | 7.699134985078978  |
|     bedrooms     |  None |  28948.527746351134 | 9395.728891110177  |
|    bathrooms     |  None |  65661.20723969836  | 10795.338070247015 |
|       lat        |  None |  704762.1484430869  |        nan         |
|       long       |  None | -137780.02000717327 |        nan         |
|  bed_bath_rooms  |  None |  -8478.364107167803 | 2858.9539125640354 |
| bedrooms_squared |  None |  -6072.384661904947 | 1494.9704277794906 |
| log_sqft_living  |  None |  -563467.7842801767 | 17567.823081204006 |
|  lat_plus_long   |  None |  -83217.19791002883 |        nan         |
+------------------+-------+---------------------+--------------------+
[10 rows x 4 columns]

#### Function for getting the RSS values from the rmse values for the training dataset

In [40]:
def get_rss_from_rmse (model, data):
    RMSE_Model = model.evaluate(data);
    RSS_Model = RMSE_Model['rmse']*RMSE_Model['rmse']*len(data);
    return RSS_Model

In [47]:
RSS_train_data_Model1 = get_rss_from_rmse(model1, train_data)
RSS_train_data_Model2= get_rss_from_rmse(model2, train_data)
RSS_train_data_Model3 = get_rss_from_rmse(model3, train_data)
print (RSS_train_data_Model1)
print (RSS_train_data_Model2)
print (RSS_train_data_Model3)

971328233545434.0
961592067859821.5
905276314551640.4

#### Function for getting the RSS values from the rmse values for the testing dataset

In [48]:
RSS_test_data_Model1 = get_rss_from_rmse(model1, test_data)
RSS_test_data_Model2 = get_rss_from_rmse(model2, test_data)
RSS_test_data_Model3 = get_rss_from_rmse(model3, test_data)
print (RSS_test_data_Model1)
print (RSS_test_data_Model2)
print (RSS_test_data_Model3)

226568089093160.4
224368799994313.0
251829318963157.3

#### New Function for getting the RSS values(from their definition) on the training dataset

In [43]:
def get_rss(model,data,output):
    predicted = model.predict(data);
    residual = output - predicted;
    rss = sum(residual*residual);
    return rss

In [51]:
RSS_bydef_model1 = get_rss(model1,train_data,train_data['price'])
RSS_bydef_model2 = get_rss(model2,train_data,train_data['price'])
RSS_bydef_model3 = get_rss(model3,train_data,train_data['price'])
print(RSS_bydef_model1)
print(RSS_bydef_model2)
print(RSS_bydef_model3)

971328233545431.0
961592067859824.0
905276314551643.9

#### New Function for getting the RSS values(from their definition) on the testing dataset

In [50]:
RSS_bydef_model1 = get_rss(model1,test_data,test_data['price'])
RSS_bydef_model2 = get_rss(model2,test_data,test_data['price'])
RSS_bydef_model3 = get_rss(model3,test_data,test_data['price'])
print(RSS_bydef_model1)
print(RSS_bydef_model2)
print(RSS_bydef_model3)

226568089093160.66
224368799994313.44
251829318963157.06